In [1]:
import numpy as np

In [2]:
x = np.array([3, 4, 5, 6])
np.sum(x)

18

In [3]:
x=np.array([[2, 2], [2, 2]])
x.sum(axis=0)

array([4, 4])

In [4]:
x.sum(axis=1)

array([4, 4])

In [5]:
x=np.array([3, 4, 5, 6 ,9])
x.min()

3

In [6]:
x.max()

9

In [7]:
x.argmax()

4

In [8]:
x.argmin()

0

In [9]:
a= np.zeros((100, 100))
np.any(a !=0)

False

In [10]:
np.all(a == a)

True

In [11]:
a=np.array([1, 1, 1, 1])
b=np.array([2, 2, 2, 2])
c=np.array([3, 3, 3, 3])
((a <= b) & (b <= c)).all()

True

In [12]:
a=np.array([1,2,4])
print(a)

[1 2 4]


In [13]:
a=np.array([(1,2,3),(4,5,6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [14]:
np.zeros(2)

array([0., 0.])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.empty(4)

array([0., 0., 0., 0.])

In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
np.arange(3,10,3)

array([3, 6, 9])

In [19]:
np.linspace(0, 15, num=5)

array([ 0.  ,  3.75,  7.5 , 11.25, 15.  ])

In [20]:
x=np.ones(2, dtype=np.int64)

In [21]:
print(x)

[1 1]


In [22]:
arr=np.array([3, 2, 5, 1, 4, 7, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
a=np.array([1, 2, 3, 4, 5,6])
b=np.array([5, 6, 7, 8, 9])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 5, 6, 7, 8, 9])

In [24]:
x=np.array([[1, 2],[3, 4]])
y=np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
 array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],                 
                            [4, 5, 6, 7]],                        
                           
                           [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])

In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
print(a)

[1 2 3 4 5 6]


In [30]:
b= a.reshape(3, 2)

In [31]:
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [32]:
a=np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
a2=a[np.newaxis, :]
a2.shape

(1, 6)

In [34]:
row_vector=a[np.newaxis, :]
row_vector.shape


(1, 6)

In [35]:
col_vector=a[:, np.newaxis]
col_vector.shape

(6, 1)

In [36]:
a=np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [37]:
b=np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [38]:
c=np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [39]:
data=np.array([1, 2])
ones=np.ones(2, dtype=int)
data+ones

array([2, 3])

In [40]:
data-ones

array([0, 1])

In [41]:
data*ones

array([1, 2])

In [42]:
data/data

array([1., 1.])

In [43]:
data*data

array([1, 4])

In [44]:
a=np.array([1, 2, 3, 4])

In [45]:
a.sum()

10

In [46]:
data=np.array([1.0, 3.0])
data * 1.5

array([1.5, 4.5])

In [47]:
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reversed_arr=np.flip(arr)

In [48]:
print("Reversed_array: ", reversed_arr)

Reversed_array:  [9 8 7 6 5 4 3 2 1]
